name: Release

on:
  release:
    types:
      - created

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PSWD }}
      run: |
        twine upload -u TWINE_USERNAME -p TWINE_PASSWORD dist/*

    - name: Upload .tar.gz to GitHub release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/cmdgpt-${{ github.event.release.tag_name }}.tar.gz
        asset_name: cmdgpt-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload .whl to GitHub release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/cmdgpt-${{ github.event.release.tag_name }}-py3-none-any.whl
        asset_name: cmdgpt-${{ github.event.release.tag_name }}-py3-none-any.whl
        asset_content_type: application/zip
